// El cliente queda disponible globalmente para integrar cada sección en fases.
// Ejemplo futuro: await window.supabaseClient.from('products').select('*')
let products = [];
const supabaseClient = window.supabaseClient || null;
if (!supabaseClient) console.warn('No se pudo inicializar Supabase. El catálogo no está disponible.');
let categories = ['Todos'];
let remoteCategories = [];
let remoteBrands = [];
const PRODUCT_IMAGE_FALLBACK = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='600' height='600' viewBox='0 0 600 600'%3E%3Crect width='600' height='600' fill='%23f1eee5'/%3E%3Cpath d='M205 190h190v220H205z' fill='%23d9cfb9'/%3E%3Cpath d='M240 250h120M240 295h90M240 340h110' stroke='%23154b40' stroke-width='14' stroke-linecap='round'/%3E%3C/svg%3E";
const CART_STORAGE_KEY='sanmartin_ecommerce_cart_v1';
function leerCarrito(){try{const raw=JSON.parse(localStorage.getItem(CART_STORAGE_KEY)||'[]'),uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;return Array.isArray(raw)?raw.filter(item=>item&&uuid.test(String(item.producto_id))&&Number.isFinite(Number(item.cantidad))&&Number(item.cantidad)>0).map(item=>({...item,cantidad:Math.min(99,Math.max(1,Math.floor(Number(item.cantidad)))),precioOriginal:Math.max(0,Number(item.precioOriginal)||0),precioOferta:item.precioOferta===null?null:Math.max(0,Number(item.precioOferta)||0),precio:Math.max(0,Number(item.precio)||0)})):[]}catch{return[]}}
function guardarCarrito(){localStorage.setItem(CART_STORAGE_KEY,JSON.stringify(cart))}
let activeCategory='Todos', activeBrandSlug='', maxPrice=250, query='', cart=leerCarrito();
const filterState={sort:'',categoryId:null,subcategories:new Set(),brands:new Set(),colors:new Set(),pieces:new Set(),featured:false,minPrice:null,maxPrice:null};
const PRODUCTS_PER_PAGE=20;
let currentPage=1;
function renderCategoryDescription(){const section=document.querySelector('#categoryDescription');if(!section)return;let categoryId=filterState.categoryId;if(filterState.subcategories.size===1)categoryId=[...filterState.subcategories][0];const category=categoryById(categoryId);const description=category?.descripcion?.trim();section.hidden=!description;if(!description)return;document.querySelector('#categoryDescriptionTitle').textContent=category.nombre;document.querySelector('#categoryDescriptionText').textContent=description;}
let selectedDelivery='', selectedPayment='',favoriteIds=new Set();
const hasCatalogPage = Boolean(document.querySelector('#productGrid'));
const pageParams = new URLSearchParams(window.location.search);
query = pageParams.get('buscar') || '';
activeBrandSlug = pageParams.get('marca') || '';
if(hasCatalogPage&&pageParams.get('destacados')==='1')filterState.featured=true;
const money=n=>`Q${n.toFixed(2)}`;
function card(p){const description=p.description?.trim()||'Información y presentación disponibles próximamente.',saved=favoriteIds.has(String(p.id)),detail=`producto.html?slug=${encodeURIComponent(p.slug||'')}`;return `<article class="product-card"><button class="favorite ${saved?'is-saved':''}" data-favorite-id="${escapeHtml(String(p.id))}" aria-label="${saved?'Quitar':'Agregar'} ${escapeHtml(p.name)} ${saved?'de':'a'} favoritos">${saved?'♥':'♡'}</button><a class="product-detail-link" href="${detail}" aria-label="Ver detalle de ${escapeHtml(p.name)}"><div class="product-image">${p.sale?`<span class="tag">Oferta -${p.discount}%</span>`:''}<img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.name)}" loading="lazy" onerror="this.src='${PRODUCT_IMAGE_FALLBACK}'"></div><div class="product-info"><span class="product-subcategory">${escapeHtml(p.category)}</span><strong class="product-name">${escapeHtml(p.name)}</strong><p class="product-description">${escapeHtml(description)}</p><div class="product-pricing">${p.sale?`<span class="old-base-price">${money(p.old)}</span><strong class="offer-price">${money(p.price)}</strong>`:`<strong class="base-price">${money(p.price)}</strong>`}</div></div></a><button class="add-button" data-id="${p.id}">Agregar al carrito <span aria-hidden="true">→</span></button></article>`}
function categoryById(id){return remoteCategories.find(category=>category.id===id);}
function rootCategoryId(id){let current=categoryById(id),guard=0;while(current?.categoria_padre_id&&guard++<20)current=categoryById(current.categoria_padre_id);return current?.id||id;}
function categoryName(id){return categoryById(id)?.nombre||'Sin categoría';}
function normalizedColor(value){return String(value||'').trim();}
function normalizeSearch(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function editDistance(a,b){const rows=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)rows[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)rows[i][j]=a[i-1]===b[j-1]?rows[i-1][j-1]:Math.min(rows[i-1][j]+1,rows[i][j-1]+1,rows[i-1][j-1]+1);return rows[a.length][b.length];}
function searchMatches(product,term){const words=normalizeSearch(term).split(' ').filter(Boolean);if(!words.length)return true;const text=normalizeSearch([product.name,product.category,product.brand?.nombre,product.description,product.color].join(' ')),tokens=text.split(' ');return words.every(word=>text.includes(word)||tokens.some(token=>word.length>3&&Math.abs(token.length-word.length)<=1&&editDistance(token,word)<=1));}
function productMatches(product,state=filterState,omit=''){const categoryId=rootCategoryId(product.categoryId),price=Number(product.price)||0,term=query.trim();if(omit!=='categoryId'&&state.categoryId&&categoryId!==state.categoryId)return false;if(omit!=='subcategories'&&state.subcategories.size&&!state.subcategories.has(product.categoryId))return false;if(omit!=='brands'&&state.brands.size&&!state.brands.has(product.brandId||''))return false;if(omit!=='colors'&&state.colors.size&&!state.colors.has(normalizedColor(product.color)))return false;if(omit!=='pieces'&&state.pieces.size&&!state.pieces.has(String(product.pieces??'')))return false;if(omit!=='featured'&&state.featured&&!product.featured)return false;if(omit!=='price'&&state.minPrice!==null&&price<state.minPrice)return false;if(omit!=='price'&&state.maxPrice!==null&&price>state.maxPrice)return false;return !term||searchMatches(product,term);}
function filtered(){const result=products.filter(product=>productMatches(product));return result.sort((a,b)=>filterState.sort==='price-asc'?a.price-b.price:filterState.sort==='price-desc'?b.price-a.price:a.order-b.order||a.name.localeCompare(b.name));}
function bindAddToCartButtons(){document.querySelectorAll('.add-button').forEach(button=>button.addEventListener('click',()=>addToCart(button.dataset.id)));}
function bindFavoriteButtons(){document.querySelectorAll('[data-favorite-id]').forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.favoriteId)));}
async function loadFavoriteIds(){if(!supabaseClient)return;const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {data}=await supabaseClient.from('favoritos_ecommerce').select('producto_id').eq('usuario_id',user.id);favoriteIds=new Set((data||[]).map(item=>String(item.producto_id)));renderProducts();renderFeaturedProducts();}
async function toggleFavorite(productId){const {data:{user}}=await supabaseClient.auth.getUser();if(!user){window.location.href=`login.html?returnTo=${encodeURIComponent(window.location.pathname.split('/').pop()||'index.html')}`;return}const exists=favoriteIds.has(String(productId)),query=supabaseClient.from('favoritos_ecommerce');const {error}=exists?await query.delete().eq('usuario_id',user.id).eq('producto_id',productId):await query.insert({usuario_id:user.id,producto_id:productId});if(error)return showToast(error.message);exists?favoriteIds.delete(String(productId)):favoriteIds.add(String(productId));renderProducts();renderFeaturedProducts();showToast(exists?'Producto eliminado de favoritos':'Producto guardado en favoritos');}
function paginationItems(totalPages){if(totalPages<=7)return Array.from({length:totalPages},(_,index)=>index+1);const pages=new Set([1,totalPages,currentPage-1,currentPage,currentPage+1]);const ordered=[...pages].filter(page=>page>=1&&page<=totalPages).sort((a,b)=>a-b),items=[];ordered.forEach((page,index)=>{if(index&&page-ordered[index-1]>1)items.push('…');items.push(page)});return items;}
function renderPagination(totalPages){const markup=totalPages<=1?'':`<button type="button" class="pagination-arrow" data-page="${currentPage-1}" ${currentPage===1?'disabled':''} aria-label="Página anterior">‹</button>${paginationItems(totalPages).map(item=>item==='…'?'<span class="pagination-ellipsis">…</span>':`<button type="button" class="pagination-page ${item===currentPage?'is-current':''}" data-page="${item}" ${item===currentPage?'aria-current="page"':''}>${item}</button>`).join('')}<button type="button" class="pagination-arrow" data-page="${currentPage+1}" ${currentPage===totalPages?'disabled':''} aria-label="Página siguiente">›</button>`;document.querySelectorAll('.catalog-pagination').forEach(nav=>nav.innerHTML=markup);}
function renderProducts(){if(!hasCatalogPage)return;const list=filtered(),totalPages=Math.max(1,Math.ceil(list.length/PRODUCTS_PER_PAGE));currentPage=Math.min(Math.max(1,currentPage),totalPages);const pageProducts=list.slice((currentPage-1)*PRODUCTS_PER_PAGE,currentPage*PRODUCTS_PER_PAGE),label=`${list.length} producto${list.length===1?'':'s'}`;document.querySelector('#productGrid').innerHTML=list.length?pageProducts.map(card).join(''):'<p class="catalog-empty">No encontramos productos con estos filtros. Prueba a eliminar alguno.</p>';const count=document.querySelector('#filterResultCount'),mobileCount=document.querySelector('#mobileProductTotal'),mobileSort=document.querySelector('#mobileSort');if(count)count.textContent=label;if(mobileCount)mobileCount.textContent=label;if(mobileSort)mobileSort.value=filterState.sort;renderPagination(list.length?totalPages:0);bindAddToCartButtons();bindFavoriteButtons();}
function facetValues(key){const base=products.filter(product=>productMatches(product,filterState,key));const values=new Map();const add=(value,label)=>{if(value===null||value===undefined||value==='')return;const item=values.get(String(value))||{value:String(value),label,count:0};item.count++;values.set(String(value),item)};base.forEach(product=>{if(key==='categoryId')add(rootCategoryId(product.categoryId),categoryName(rootCategoryId(product.categoryId)));if(key==='subcategories'&&filterState.categoryId&&rootCategoryId(product.categoryId)===filterState.categoryId&&product.categoryId!==filterState.categoryId)add(product.categoryId,categoryName(product.categoryId));if(key==='brands'&&product.brandId)add(product.brandId,product.brand?.nombre||'Sin marca');if(key==='colors')add(normalizedColor(product.color),normalizedColor(product.color));if(key==='pieces'&&Number.isFinite(Number(product.pieces))&&Number(product.pieces)>0)add(String(product.pieces),`${product.pieces} pieza${Number(product.pieces)===1?'':'s'}`)});return [...values.values()].sort((a,b)=>a.label.localeCompare(b.label,'es'));}
function accordion(title,body,{open=false,hidden=false}={}){return hidden?'':`<details class="filter-accordion" ${open?'open':''}><summary>${title}<span aria-hidden="true">⌄</span></summary>${body}</details>`;}
function selectableOptions(key,options,{multiple=true}={}){if(!options.length)return '<p class="filter-empty">Sin opciones disponibles.</p>';const selected=filterState[key];return `<div class="filter-options">${options.map(option=>{const isSelected=multiple?selected.has(option.value):selected===option.value;return `<label class="filter-option ${isSelected?'is-selected':''}"><input type="${multiple?'checkbox':'radio'}" name="${key}" value="${escapeHtml(option.value)}" ${isSelected?'checked':''} data-smart-filter="${key}"><span>${escapeHtml(option.label)}</span><small>${option.count}</small></label>`}).join('')}</div>`;}
function renderActiveFilterChips(){const host=document.querySelector('#activeFilterChips');if(!host)return;const chips=[];if(filterState.categoryId)chips.push(['categoryId',filterState.categoryId,categoryName(filterState.categoryId)]);[['subcategories',filterState.subcategories],['brands',filterState.brands],['colors',filterState.colors],['pieces',filterState.pieces]].forEach(([key,values])=>values.forEach(value=>chips.push([key,value,key==='subcategories'?categoryName(value):key==='brands'?(remoteBrands.find(brand=>brand.id===value)?.nombre||'Marca'):key==='pieces'?`${value} piezas`:value])));if(filterState.minPrice!==null||filterState.maxPrice!==null)chips.push(['price','',`Precio ${filterState.minPrice!==null?money(filterState.minPrice):'mín.'} – ${filterState.maxPrice!==null?money(filterState.maxPrice):'máx.'}`]);host.innerHTML=chips.map(([key,value,label])=>`<button type="button" class="filter-chip" data-remove-filter="${key}" data-value="${escapeHtml(value)}">${escapeHtml(label)} ×</button>`).join('');}
function renderFilters(){if(!hasCatalogPage)return;const host=document.querySelector('#smartFilters');if(!host)return;const prices=products.map(product=>Number(product.price)).filter(Number.isFinite),min=Math.floor(Math.min(...prices,0)),max=Math.ceil(Math.max(...prices,0));const categoryOptions=facetValues('categoryId'),subcategoryOptions=facetValues('subcategories'),brandOptions=facetValues('brands'),colorOptions=facetValues('colors'),pieceOptions=facetValues('pieces');host.innerHTML=accordion('Ordenar por',`<div class="filter-options sort-options"><label class="filter-option"><input type="radio" name="sort" value="price-asc" ${filterState.sort==='price-asc'?'checked':''} data-smart-sort><span>Precio: menor a mayor</span></label><label class="filter-option"><input type="radio" name="sort" value="price-desc" ${filterState.sort==='price-desc'?'checked':''} data-smart-sort><span>Precio: mayor a menor</span></label></div>`,{open:true})+accordion('Categoría',selectableOptions('categoryId',categoryOptions,{multiple:false}),{open:true})+accordion('Subcategorías',selectableOptions('subcategories',subcategoryOptions),{hidden:!filterState.categoryId||!subcategoryOptions.length})+accordion('Marca',selectableOptions('brands',brandOptions),{hidden:!brandOptions.length})+accordion('Color',selectableOptions('colors',colorOptions),{hidden:!colorOptions.length})+accordion('Número de piezas',selectableOptions('pieces',pieceOptions),{hidden:!pieceOptions.length})+accordion('Precio',`<p class="filter-hint">Rango disponible: ${money(min)} – ${money(max)}</p><div class="price-inputs"><label>Desde<input type="number" inputmode="decimal" min="${min}" max="${max}" value="${filterState.minPrice??''}" placeholder="${min}" data-price-bound="min"></label><label>Hasta<input type="number" inputmode="decimal" min="${min}" max="${max}" value="${filterState.maxPrice??''}" placeholder="${max}" data-price-bound="max"></label></div>`);renderActiveFilterChips();}
function refreshCatalog(resetPage=true){if(resetPage)currentPage=1;renderCatalogDiscovery();renderFilters();renderProducts();renderCategoryDescription();}
function renderCatalogDiscovery(){
  if(!hasCatalogPage)return;
  const section=document.querySelector('#catalogDiscoverySection'),title=document.querySelector('#catalogDiscoveryTitle'),host=document.querySelector('#catalogDiscovery');
  if(!section||!title||!host)return;
  const childrenOf=id=>remoteCategories.filter(category=>category.categoria_padre_id===id);
  const imageFor=category=>category?.imagen_url?`<img src="${escapeHtml(safeImageUrl(category.imagen_url))}" alt="" loading="lazy">`:`<span class="catalog-discovery-monogram">${escapeHtml((category?.icono||category?.nombre||'?').slice(0,1).toUpperCase())}</span>`;
  const hasProduct=(predicate,omit)=>products.some(product=>predicate(product)&&productMatches(product,filterState,omit));
  let mode='category',items=[],label='Explora por categoría';
  if(!filterState.categoryId){
    items=remoteCategories.filter(category=>!category.categoria_padre_id&&hasProduct(product=>rootCategoryId(product.categoryId)===category.id,'categoryId'));
  }else{
    const children=childrenOf(filterState.categoryId);
    if(children.length&&!filterState.subcategories.size){
      mode='subcategory';
      items=children.filter(category=>hasProduct(product=>product.categoryId===category.id,'subcategories'));
      label=`Subcategorías de ${categoryName(filterState.categoryId)}`;
    }else{
      mode='brand';
      items=facetValues('brands').map(option=>remoteBrands.find(brand=>brand.id===option.value)).filter(Boolean);
      label='Marcas disponibles';
    }
  }
  if(!items.length){section.hidden=true;return;}
  section.hidden=false;title.textContent=label;
  host.innerHTML=items.map(item=>{const selected=mode==='brand'?filterState.brands.has(item.id):mode==='subcategory'?filterState.subcategories.has(item.id):filterState.categoryId===item.id;const kind=mode==='brand'?'brand':mode;const visual=mode==='brand'?(item.logo_url?`<img src="${escapeHtml(safeImageUrl(item.logo_url))}" alt="" loading="lazy">`:`<span class="catalog-discovery-monogram">${escapeHtml(brandInitial(item.nombre))}</span>`):imageFor(item);return `<button type="button" class="catalog-discovery-card ${selected?'is-selected':''}" data-catalog-discovery="${kind}" data-id="${item.id}" aria-pressed="${selected}"><span class="catalog-discovery-image">${visual}</span><strong>${escapeHtml(item.nombre)}</strong></button>`;}).join('');
  if(!host.dataset.bound){host.dataset.bound='true';host.addEventListener('click',event=>{const button=event.target.closest('[data-catalog-discovery]');if(!button)return;const kind=button.dataset.catalogDiscovery,id=button.dataset.id;if(kind==='category'){filterState.categoryId=id;filterState.subcategories.clear();filterState.brands.clear();activeCategory=categoryName(id);}else if(kind==='subcategory'){filterState.subcategories.has(id)?filterState.subcategories.delete(id):filterState.subcategories.add(id);filterState.brands.clear();}else if(kind==='brand'){filterState.brands.has(id)?filterState.brands.delete(id):filterState.brands.add(id);}refreshCatalog();});}
  setupCatalogDiscoveryCarousel();
}
function setupCatalogDiscoveryCarousel(){
  const track=document.querySelector('#catalogDiscovery'),previous=document.querySelector('#catalogDiscoveryPrevious'),next=document.querySelector('#catalogDiscoveryNext');
  if(!track||!previous||!next)return;
  const update=()=>{const overflow=track.scrollWidth-track.clientWidth>4;previous.hidden=!overflow;next.hidden=!overflow;previous.disabled=track.scrollLeft<=2;next.disabled=!overflow||track.scrollLeft+track.clientWidth>=track.scrollWidth-2;};
  if(!track.dataset.carouselBound){
    track.dataset.carouselBound='true';
    previous.addEventListener('click',()=>track.scrollBy({left:-Math.max(180,track.clientWidth*.72),behavior:'smooth'}));
    next.addEventListener('click',()=>track.scrollBy({left:Math.max(180,track.clientWidth*.72),behavior:'smooth'}));
    track.addEventListener('scroll',update,{passive:true});
    if('ResizeObserver' in window)new ResizeObserver(update).observe(track);
  }
  requestAnimationFrame(update);
}
function setCategoryByName(name){const category=remoteCategories.find(item=>item.nombre===name);filterState.categoryId=category?rootCategoryId(category.id):null;filterState.subcategories.clear();activeCategory=name||'Todos';refreshCatalog();}
function selectCategoryFromHeader(name){const category=remoteCategories.find(item=>item.nombre===name);if(!category){filterState.categoryId=null;filterState.subcategories.clear();activeCategory='Todos';refreshCatalog();return;}const rootId=rootCategoryId(category.id);filterState.categoryId=rootId;filterState.subcategories.clear();if(category.id!==rootId)filterState.subcategories.add(category.id);activeCategory=categoryName(rootId);refreshCatalog();}
function escapeHtml(value=''){const element=document.createElement('span');element.textContent=value;return element.innerHTML;}
function safeImageUrl(value){const source=String(value||'').trim();return /^(https?:\/\/|data:image\/svg\+xml,)/i.test(source)?source:PRODUCT_IMAGE_FALLBACK;}
function renderCategoryNavigation(){const nav=document.querySelector('#categoryNav');if(!remoteCategories.length){nav.innerHTML='<span class="nav-loading">No hay categorías disponibles.</span>';return;}const childrenOf=id=>remoteCategories.filter(category=>category.categoria_padre_id===id);const roots=remoteCategories.filter(category=>!category.categoria_padre_id);const categoryHref=category=>hasCatalogPage?'#catalogo':`catalogo.html?categoria=${encodeURIComponent(category.slug)}`;const link=category=>`<a href="${categoryHref(category)}" data-category="${escapeHtml(category.nombre)}" data-category-id="${category.id}">${category.icono?`<span aria-hidden="true">${escapeHtml(category.icono)}</span> `:''}${escapeHtml(category.nombre)}</a>`;const allHref=hasCatalogPage?'#catalogo':'catalogo.html';nav.innerHTML=`<a href="${allHref}" data-category="Todos">Todo el catálogo</a>${roots.map(parent=>{const children=childrenOf(parent.id);if(!children.length)return link(parent);const panelId=`subcategorias-${parent.id}`,viewAll=`<a class="subnav-view-all" href="${categoryHref(parent)}" data-category="${escapeHtml(parent.nombre)}" data-category-id="${parent.id}">Ver todo</a>`;return `<div class="nav-dropdown"><a class="nav-parent-link" href="${categoryHref(parent)}" data-category="${escapeHtml(parent.nombre)}" data-category-id="${parent.id}">${escapeHtml(parent.nombre)}</a><button class="nav-parent" type="button" aria-expanded="false" aria-controls="${panelId}" aria-label="Mostrar subcategorías de ${escapeHtml(parent.nombre)}" data-subnav-toggle><span>${escapeHtml(parent.nombre)}</span><span class="subnav-toggle" aria-hidden="true" data-subnav-icon>⌄</span></button><div class="subnav" id="${panelId}">${viewAll}${children.map(link).join('')}</div></div>`}).join('')}<a href="${hasCatalogPage?'index.html#destacados':'#destacados'}" class="sale-link">Destacados</a>`;bindSubcategoryToggles();}
function bindSubcategoryToggles(){document.querySelectorAll('[data-subnav-toggle]').forEach(button=>button.addEventListener('click',()=>{const dropdown=button.closest('.nav-dropdown'),willOpen=!dropdown.classList.contains('open');dropdown.classList.toggle('open',willOpen);button.setAttribute('aria-expanded',String(willOpen));button.setAttribute('aria-label',`${willOpen?'Ocultar':'Mostrar'} subcategorías`);button.querySelector('[data-subnav-icon]').textContent=willOpen?'⌃':'⌄';}));}
async function loadCategoriesFromSupabase(){if(!supabaseClient)return;const {data,error}=await supabaseClient.from('categorias').select('id,nombre,slug,categoria_padre_id,imagen_url,orden,icono').eq('activo',true).eq('visible_ecommerce',true).order('orden',{ascending:true,nullsFirst:false}).order('nombre',{ascending:true});if(error){console.error('No se pudieron cargar las categorías de Supabase:',error.message);document.querySelector('#categoryNav').innerHTML='<span class="nav-loading">Las categorías estarán disponibles pronto.</span>';return;}remoteCategories=data||[];categories=['Todos',...remoteCategories.map(category=>category.nombre)];const requestedSlug=pageParams.get('categoria');const requestedCategory=remoteCategories.find(category=>category.slug===requestedSlug);if(requestedCategory)activeCategory=requestedCategory.nombre;if(activeCategory!=='Todos'&&!categories.includes(activeCategory))activeCategory='Todos';renderCategoryNavigation();renderCategoryCarousel();renderCatalogDiscovery();renderFilters();renderProducts();}
function productImage(image){if(!image)return PRODUCT_IMAGE_FALLBACK;if(image.url_publica)return image.url_publica;if(image.storage_bucket&&image.storage_path&&supabaseClient)return supabaseClient.storage.from(image.storage_bucket).getPublicUrl(image.storage_path).data.publicUrl;return PRODUCT_IMAGE_FALLBACK;}
function activeOfferFor(productId,offers){const now=Date.now();return offers.filter(offer=>offer.producto_id===productId&&offer.activo&&offer.aplica_ecommerce&&new Date(offer.fecha_inicio).getTime()<=now&&(!offer.fecha_fin||new Date(offer.fecha_fin).getTime()>=now)).sort((a,b)=>Number(b.oferta_porcentaje)-Number(a.oferta_porcentaje))[0];}
async function loadProductsFromSupabase(){if(!supabaseClient)return;const loading=hasCatalogPage?document.querySelector('#productGrid'):document.querySelector('#featuredProducts');if(loading)loading.innerHTML='<p class="catalog-empty">Cargando productos…</p>';const [productResult,imageResult,offerResult]=await Promise.all([supabaseClient.from('catalogo_productos').select('id,nombre,nombre_corto,slug,categoria_id,marca_id,descripcion_corta,precio_base,destacado_ecommerce,orden_ecommerce,color,piezas_por_paquete,sku').order('orden_ecommerce',{ascending:true,nullsFirst:false}).order('nombre',{ascending:true}),supabaseClient.from('producto_imagenes').select('producto_id,url_publica,storage_bucket,storage_path,orden,es_principal,activo').eq('activo',true).order('es_principal',{ascending:false}).order('orden',{ascending:true,nullsFirst:false}),supabaseClient.from('ofertas_producto').select('producto_id,oferta_porcentaje,fecha_inicio,fecha_fin,activo,aplica_ecommerce').eq('activo',true).eq('aplica_ecommerce',true)]);if(productResult.error){console.error('No se pudieron cargar los productos:',productResult.error.message);if(loading)loading.innerHTML='<p class="catalog-empty">No pudimos cargar el catálogo. Inténtalo nuevamente.</p>';return;}if(imageResult.error)console.warn('Las imágenes no se pudieron cargar:',imageResult.error.message);if(offerResult.error)console.warn('Las ofertas no se pudieron cargar:',offerResult.error.message);const imagesByProduct=new Map();(imageResult.data||[]).forEach(image=>{if(!imagesByProduct.has(image.producto_id))imagesByProduct.set(image.producto_id,image)});const categoryById=new Map(remoteCategories.map(category=>[category.id,category])),brandById=new Map(remoteBrands.map(brand=>[brand.id,brand]));products=(productResult.data||[]).map(row=>{const original=Math.max(0,Number(row.precio_base)||0),offer=activeOfferFor(row.id,offerResult.data||[]),discount=Math.min(100,Math.max(0,Number(offer?.oferta_porcentaje)||0)),price=discount?Number((original*(1-discount/100)).toFixed(2)):original,category=categoryById.get(row.categoria_id),brand=brandById.get(row.marca_id);return{id:row.id,slug:row.slug||'',sku:row.sku||'',name:row.nombre_corto||row.nombre,description:row.descripcion_corta||'',category:category?.nombre||'Sin categoría',categoryId:row.categoria_id,brand,brandId:row.marca_id,image:productImage(imagesByProduct.get(row.id)),price,old:discount?original:null,sale:discount>0,discount,featured:Boolean(row.destacado_ecommerce),order:Number(row.orden_ecommerce)||0,color:row.color||null,pieces:row.piezas_por_paquete||null};});const highest=Math.max(250,...products.map(product=>product.price));const range=document.querySelector('#priceRange');if(range){maxPrice=Math.ceil(highest/50)*50;range.max=maxPrice;range.value=maxPrice;document.querySelector('#priceOutput').textContent=`Q${maxPrice}`;}renderProducts();renderFeaturedProducts();}
function renderFeaturedProducts(){const container=document.querySelector('#featuredProducts');if(!container)return;const featured=products.filter(product=>product.featured).sort((a,b)=>a.order-b.order);if(!featured.length){container.classList.remove('is-looping');container.innerHTML='<p class="catalog-empty">Pronto tendremos productos destacados.</p>';return;}const loopProducts=featured.length>1?[...featured,...featured]:featured;container.classList.toggle('is-looping',featured.length>1);container.innerHTML=loopProducts.map(card).join('');bindAddToCartButtons();bindFavoriteButtons();}
function setupDraggableCarousels(){const carousels=[['.featured-marquee-viewport','#featuredProducts'],['.brand-marquee-viewport','#brandTrack'],['.category-marquee-viewport','#categoryTrack']];carousels.forEach(([viewportSelector,trackSelector])=>{const viewport=document.querySelector(viewportSelector),track=document.querySelector(trackSelector);if(!viewport||!track||viewport.dataset.dragReady)return;viewport.dataset.dragReady='true';viewport.classList.add('is-draggable-carousel');let pointerId=null,startX=0,startScroll=0,pauseUntil=0,lastFrame=0,isDragging=false,ignoreNextClick=false;const pause=milliseconds=>{pauseUntil=Date.now()+milliseconds};const normalizeLoop=()=>{const loopWidth=track.scrollWidth/2;if(loopWidth&&viewport.scrollLeft>=loopWidth)viewport.scrollLeft-=loopWidth};const animate=time=>{if(lastFrame&&Date.now()>=pauseUntil&&track.scrollWidth>viewport.clientWidth){const elapsed=Math.min(32,time-lastFrame);viewport.scrollLeft+=elapsed*.025;normalizeLoop()}lastFrame=time;requestAnimationFrame(animate)};requestAnimationFrame(animate);viewport.addEventListener('pointerdown',event=>{if(event.button!==undefined&&event.button!==0)return;pointerId=event.pointerId;startX=event.clientX;startScroll=viewport.scrollLeft;isDragging=false;pause(2600);});viewport.addEventListener('pointermove',event=>{if(event.pointerId!==pointerId)return;const distance=event.clientX-startX;if(!isDragging&&Math.abs(distance)>6){isDragging=true;viewport.setPointerCapture(pointerId);viewport.classList.add('is-dragging');}if(!isDragging)return;event.preventDefault();viewport.scrollLeft=startScroll-distance;pause(2600);});const finishDrag=event=>{if(event.pointerId!==pointerId)return;const dragged=isDragging;if(viewport.hasPointerCapture(pointerId))viewport.releasePointerCapture(pointerId);viewport.classList.remove('is-dragging');pointerId=null;isDragging=false;pause(1800);if(dragged){ignoreNextClick=true;setTimeout(()=>ignoreNextClick=false,0);}};viewport.addEventListener('pointerup',finishDrag);viewport.addEventListener('pointercancel',finishDrag);viewport.addEventListener('click',event=>{if(!ignoreNextClick)return;event.preventDefault();event.stopImmediatePropagation();},{capture:true});viewport.addEventListener('mouseenter',()=>pause(999999));viewport.addEventListener('mouseleave',()=>pause(700));});}
function subscribeToCategoryChanges(){if(!supabaseClient)return;supabaseClient.channel('ecommerce-categorias').on('postgres_changes',{event:'*',schema:'public',table:'categorias'},async()=>{await loadCategoriesFromSupabase();loadProductsFromSupabase();}).subscribe(status=>{if(status==='CHANNEL_ERROR')console.warn('Realtime para categorías no está habilitado en Supabase.');});}
function renderCategoryCarousel(){const track=document.querySelector('#categoryTrack');if(!track)return;const roots=remoteCategories.filter(category=>!category.categoria_padre_id&&category.slug);if(!roots.length){track.classList.remove('is-looping');track.innerHTML='<p class="catalog-empty">Pronto encontrarás nuestras categorías.</p>';return;}const loopCategories=roots.length>1?[...roots,...roots]:roots;track.classList.toggle('is-looping',roots.length>1);track.innerHTML=loopCategories.map(category=>`<a class="category-card" href="catalogo.html?categoria=${encodeURIComponent(category.slug)}" aria-label="Ver productos de ${escapeHtml(category.nombre)}"><span class="category-image">${category.imagen_url?`<img src="${escapeHtml(category.imagen_url)}" alt="${escapeHtml(category.nombre)}" loading="lazy">`:`<span class="category-monogram">${escapeHtml(category.icono||category.nombre.slice(0,1).toUpperCase())}</span>`}</span><strong>${escapeHtml(category.nombre)}</strong><small>Explorar →</small></a>`).join('');}
async function loadProductFacets(){/* Los atributos públicos ya llegan desde catalogo_productos. */}
setTimeout(()=>loadProductFacets(),750);
setTimeout(loadFavoriteIds,900);
async function loadCategoryDescriptions(attempt=0){if(!supabaseClient)return;if(!remoteCategories.length){if(attempt<20)setTimeout(()=>loadCategoryDescriptions(attempt+1),250);return;}const {data,error}=await supabaseClient.from('categorias').select('id,descripcion').eq('activo',true).eq('visible_ecommerce',true);if(error){console.warn('No se pudieron cargar las descripciones de categorías:',error.message);return;}const descriptions=new Map((data||[]).map(category=>[category.id,category.descripcion]));remoteCategories=remoteCategories.map(category=>({...category,descripcion:descriptions.get(category.id)||null}));refreshCatalog(false);}
setTimeout(()=>loadCategoryDescriptions(),800);
let editorialPromos=[];
function editorialPromoImage(item){if(item.imagen_url)return item.imagen_url;if(item.storage_bucket&&item.storage_path&&supabaseClient)return supabaseClient.storage.from(item.storage_bucket).getPublicUrl(item.storage_path).data.publicUrl;return '';}
function renderCategoryPromo(){const section=document.querySelector('.category-promo-section'),promo=document.querySelector('#categoryPromo');if(!section||!promo)return;if(!editorialPromos.length){section.hidden=true;return;}section.hidden=false;const savedId=sessionStorage.getItem('sanmartin_editorial_promo_id');let item=editorialPromos.find(promo=>promo.id===savedId);if(!item){item=editorialPromos[Math.floor(Math.random()*editorialPromos.length)];sessionStorage.setItem('sanmartin_editorial_promo_id',item.id);}const image=editorialPromoImage(item);promo.innerHTML=`<div class="category-promo-copy">${item.etiqueta?`<p class="eyebrow">${escapeHtml(item.etiqueta)}</p>`:''}<h2>${escapeHtml(item.titulo)}</h2>${item.descripcion?`<p>${escapeHtml(item.descripcion)}</p>`:''}${item.cta_texto?`<a class="button category-promo-cta" href="${safeBannerUrl(item.cta_url)}">${escapeHtml(item.cta_texto)} <span aria-hidden="true">→</span></a>`:''}</div><div class="category-promo-image">${image?`<img src="${escapeHtml(image)}" alt="${escapeHtml(item.alt_text||item.titulo)}" loading="lazy">`:''}</div>`;}
async function loadEditorialPromosFromSupabase(){const section=document.querySelector('.category-promo-section');if(!section||!supabaseClient)return;const {data,error}=await supabaseClient.from('anuncios_editoriales_ecommerce').select('id,etiqueta,titulo,descripcion,cta_texto,cta_url,imagen_url,storage_bucket,storage_path,alt_text,orden,activo,fecha_inicio,fecha_fin').eq('activo',true).order('orden',{ascending:true,nullsFirst:false});if(error){console.warn('No se pudieron cargar los anuncios editoriales:',error.message);section.hidden=true;return;}const now=Date.now();editorialPromos=(data||[]).filter(item=>(!item.fecha_inicio||new Date(item.fecha_inicio).getTime()<=now)&&(!item.fecha_fin||new Date(item.fecha_fin).getTime()>=now));renderCategoryPromo();}
function subscribeToEditorialPromoChanges(){if(!supabaseClient)return;supabaseClient.channel('ecommerce-anuncios-editoriales').on('postgres_changes',{event:'*',schema:'public',table:'anuncios_editoriales_ecommerce'},loadEditorialPromosFromSupabase).subscribe(status=>{if(status==='CHANNEL_ERROR')console.warn('Realtime para anuncios editoriales no está habilitado en Supabase.');});}
function brandInitial(name=''){return name.trim().slice(0,1).toUpperCase()||'S';}
function renderBrandCarousel(){const track=document.querySelector('#brandTrack');if(!track)return;const brands=remoteBrands.filter(brand=>brand.slug);if(!brands.length){track.classList.remove('is-looping');track.innerHTML='<p class="catalog-empty">Pronto encontrarás nuestras marcas.</p>';return;}const loopBrands=brands.length>1?[...brands,...brands]:brands;track.classList.toggle('is-looping',brands.length>1);track.innerHTML=loopBrands.map(brand=>`<a class="brand-card" href="catalogo.html?marca=${encodeURIComponent(brand.slug)}" aria-label="Ver productos de ${escapeHtml(brand.nombre)}"><span class="brand-logo">${brand.logo_url?`<img src="${escapeHtml(brand.logo_url)}" alt="${escapeHtml(brand.nombre)}" loading="lazy">`:`<span class="brand-monogram">${escapeHtml(brandInitial(brand.nombre))}</span>`}</span><strong>${escapeHtml(brand.nombre)}</strong></a>`).join('');}
async function loadBrandsFromSupabase(){if(!supabaseClient)return;const {data,error}=await supabaseClient.from('marcas').select('id,nombre,slug,logo_url,destacada,orden,activo').eq('activo',true).order('orden',{ascending:true,nullsFirst:false}).order('nombre',{ascending:true});if(error){console.error('No se pudieron cargar las marcas:',error.message);const track=document.querySelector('#brandTrack');if(track)track.innerHTML='<p class="catalog-empty">Las marcas estarán disponibles pronto.</p>';return;}remoteBrands=data||[];renderBrandCarousel();renderCatalogDiscovery();}
function subscribeToProductChanges(){if(!supabaseClient)return;const refresh=()=>loadProductsFromSupabase();supabaseClient.channel('ecommerce-productos').on('postgres_changes',{event:'*',schema:'public',table:'productos'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'producto_imagenes'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'ofertas_producto'},refresh).subscribe(status=>{if(status==='CHANNEL_ERROR')console.warn('Realtime para productos no está habilitado en Supabase.');});}
function subscribeToBrandChanges(){if(!supabaseClient)return;supabaseClient.channel('ecommerce-marcas').on('postgres_changes',{event:'*',schema:'public',table:'marcas'},async()=>{await loadBrandsFromSupabase();loadProductsFromSupabase();}).subscribe(status=>{if(status==='CHANNEL_ERROR')console.warn('Realtime para marcas no está habilitado en Supabase.');});}
let homeAnnouncements=[],activeHomeAnnouncement=0,homeAnnouncementTimer=null;
const hasHomeAnnouncements=Boolean(document.querySelector('#homeAnnouncementCarousel'));
function homeAnnouncementImage(item){if(item.imagen_url)return item.imagen_url;if(item.storage_bucket&&item.storage_path&&supabaseClient)return supabaseClient.storage.from(item.storage_bucket).getPublicUrl(item.storage_path).data.publicUrl;return '';}
let homeAnnouncementSlots=[0,1,2];
function renderHomeAnnouncements(){if(!hasHomeAnnouncements)return;const section=document.querySelector('.home-announcements'),carousel=document.querySelector('#homeAnnouncementCarousel');if(!homeAnnouncements.length){section.hidden=true;return;}section.hidden=false;const slotCount=Math.min(3,homeAnnouncements.length);homeAnnouncementSlots=homeAnnouncementSlots.map((index,slot)=>slot<slotCount?(Number.isFinite(index)?index%homeAnnouncements.length:slot%homeAnnouncements.length):index);carousel.innerHTML=Array.from({length:slotCount},(_,slot)=>{const item=homeAnnouncements[homeAnnouncementSlots[slot]],image=homeAnnouncementImage(item),content=`<img src="${escapeHtml(image)}" alt="${escapeHtml(item.alt_text||item.titulo||'Anuncio destacado')}" loading="lazy">`;return `<article class="home-announcement-slide home-announcement-slot" data-announcement-slot="${slot}">${item.cta_url?`<a href="${safeBannerUrl(item.cta_url)}" aria-label="${escapeHtml(item.titulo||'Ver anuncio')}">${content}</a>`:content}${homeAnnouncements.length>1?`<button type="button" class="home-announcement-arrow previous" data-home-announcement-slot="${slot}" data-home-announcement-action="previous" aria-label="Anuncio anterior">‹</button><button type="button" class="home-announcement-arrow next" data-home-announcement-slot="${slot}" data-home-announcement-action="next" aria-label="Siguiente anuncio">›</button>`:''}</article>`;}).join('');}
function startHomeAnnouncementRotation(){if(!hasHomeAnnouncements||homeAnnouncements.length<2)return;clearInterval(homeAnnouncementTimer);homeAnnouncementTimer=setInterval(()=>{homeAnnouncementSlots=homeAnnouncementSlots.map(index=>(index+1)%homeAnnouncements.length);renderHomeAnnouncements();},5000);}
async function loadHomeAnnouncements(){if(!hasHomeAnnouncements||!supabaseClient)return;const {data,error}=await supabaseClient.from('anuncios_inicio_ecommerce').select('id,titulo,imagen_url,storage_bucket,storage_path,alt_text,cta_url,orden,activo,fecha_inicio,fecha_fin').eq('activo',true).order('orden',{ascending:true,nullsFirst:false});if(error){console.warn('No se pudieron cargar los anuncios de inicio:',error.message);return;}const now=Date.now();homeAnnouncements=(data||[]).filter(item=>(!item.fecha_inicio||new Date(item.fecha_inicio).getTime()<=now)&&(!item.fecha_fin||new Date(item.fecha_fin).getTime()>=now));activeHomeAnnouncement=0;renderHomeAnnouncements();startHomeAnnouncementRotation();}
function subscribeToHomeAnnouncementChanges(){if(!hasHomeAnnouncements||!supabaseClient)return;supabaseClient.channel('ecommerce-anuncios-inicio').on('postgres_changes',{event:'*',schema:'public',table:'anuncios_inicio_ecommerce'},loadHomeAnnouncements).subscribe(status=>{if(status==='CHANNEL_ERROR')console.warn('Realtime para anuncios de inicio no está habilitado en Supabase.');});}
if(hasHomeAnnouncements){document.querySelector('#homeAnnouncementCarousel').addEventListener('click',event=>{const button=event.target.closest('[data-home-announcement-action]');if(!button)return;event.preventDefault();const slot=Number(button.dataset.homeAnnouncementSlot);homeAnnouncementSlots[slot]=(homeAnnouncementSlots[slot]+(button.dataset.homeAnnouncementAction==='next'?1:-1)+homeAnnouncements.length)%homeAnnouncements.length;renderHomeAnnouncements();startHomeAnnouncementRotation();});}
let banners = [], activeBannerIndex = 0, bannerTimer = null;
const hasBannerCarousel = Boolean(document.querySelector('#bannerCarousel'));
function safeBannerUrl(value){if(!value)return 'catalogo.html';try{const url=new URL(value,window.location.origin);return ['http:','https:'].includes(url.protocol)?url.href:'catalogo.html'}catch{return 'catalogo.html'}}
function getBannerImage(banner){if(banner.imagen_url)return banner.imagen_url;if(banner.storage_bucket&&banner.storage_path&&supabaseClient)return supabaseClient.storage.from(banner.storage_bucket).getPublicUrl(banner.storage_path).data.publicUrl;return ''}
function renderBannerCarousel(){if(!hasBannerCarousel)return;const carousel=document.querySelector('#bannerCarousel');if(!banners.length){carousel.innerHTML='<div class="banner-empty"><p class="eyebrow">PRÓXIMAMENTE</p><h1>Nuevas promociones en camino.</h1><a class="button button-dark" href="catalogo.html">Ver catálogo</a></div>';return;}activeBannerIndex=(activeBannerIndex+banners.length)%banners.length;const banner=banners[activeBannerIndex], image=getBannerImage(banner), allowedThemes=['oscuro','claro','esmeralda','dorado','coral','nocturno'], theme=allowedThemes.includes(banner.tema)?`theme-${banner.tema}`:'theme-oscuro';carousel.innerHTML=`<article class="banner-slide ${theme}"><img class="banner-image" src="${escapeHtml(image)}" alt="${escapeHtml(banner.alt_text||banner.titulo||'Promoción San Martín')}"><div class="banner-overlay"></div><div class="banner-content"><p class="eyebrow">${escapeHtml(banner.etiqueta||'SAN MARTÍN')}</p><h1>${escapeHtml(banner.titulo||'Una promoción especial para ti')}</h1>${banner.descripcion?`<p class="banner-description">${escapeHtml(banner.descripcion)}</p>`:''}${banner.cta_texto?`<a class="button banner-cta" href="${safeBannerUrl(banner.cta_url)}">${escapeHtml(banner.cta_texto)}</a>`:''}</div>${banners.length>1?`<button class="banner-arrow previous" type="button" data-banner-action="previous" aria-label="Banner anterior">‹</button><button class="banner-arrow next" type="button" data-banner-action="next" aria-label="Siguiente banner">›</button><div class="banner-dots">${banners.map((_,index)=>`<button type="button" data-banner-index="${index}" class="${index===activeBannerIndex?'active':''}" aria-label="Ir al banner ${index+1}"></button>`).join('')}</div>`:''}</article>`;}
function startBannerRotation(){if(!hasBannerCarousel||banners.length<2)return;clearInterval(bannerTimer);bannerTimer=setInterval(()=>{activeBannerIndex=(activeBannerIndex+1)%banners.length;renderBannerCarousel()},6000)}
async function loadBannersFromSupabase(){if(!hasBannerCarousel||!supabaseClient)return;const {data,error}=await supabaseClient.from('banners_ecommerce').select('id,imagen_url,storage_bucket,storage_path,alt_text,etiqueta,titulo,descripcion,cta_texto,cta_url,tema,orden,activo,fecha_inicio,fecha_fin').eq('activo',true).order('orden',{ascending:true,nullsFirst:false});if(error){console.error('No se pudieron cargar los banners:',error.message);document.querySelector('#bannerCarousel').innerHTML='<div class="banner-empty"><p class="eyebrow">PROMOCIONES</p><h1>Muy pronto verás nuestras novedades.</h1></div>';return;}const now=Date.now();banners=(data||[]).filter(banner=>(!banner.fecha_inicio||new Date(banner.fecha_inicio).getTime()<=now)&&(!banner.fecha_fin||new Date(banner.fecha_fin).getTime()>=now));activeBannerIndex=0;renderBannerCarousel();startBannerRotation();}
function subscribeToBannerChanges(){if(!hasBannerCarousel||!supabaseClient)return;supabaseClient.channel('ecommerce-banners').on('postgres_changes',{event:'*',schema:'public',table:'banners_ecommerce'},()=>loadBannersFromSupabase()).subscribe(status=>{if(status==='CHANNEL_ERROR')console.warn('Realtime para banners no está habilitado en Supabase.');});}
if(hasBannerCarousel){document.querySelector('#bannerCarousel').addEventListener('click',event=>{const action=event.target.dataset.bannerAction,index=event.target.dataset.bannerIndex;if(action){activeBannerIndex+=action==='next'?1:-1;renderBannerCarousel();startBannerRotation()}if(index!==undefined){activeBannerIndex=Number(index);renderBannerCarousel();startBannerRotation()}});document.querySelector('#bannerCarousel').addEventListener('mouseenter',()=>clearInterval(bannerTimer));document.querySelector('#bannerCarousel').addEventListener('mouseleave',startBannerRotation);}
function addToCart(id){const product=products.find(item=>item.id===id);if(!product)return;const item=cart.find(entry=>entry.producto_id===String(product.id));if(item)item.cantidad=Math.min(99,item.cantidad+1);else{const precioOriginal=Number(product.old||product.price);const precioOferta=product.sale?Number(product.price):null;cart.push({producto_id:String(product.id),nombre:product.name,image:product.image,cantidad:1,precioOriginal,precioOferta,precio:Number(product.price),descuentoUnitario:Math.max(0,precioOriginal-Number(product.price))})}guardarCarrito();renderCart();showToast('Producto agregado al carrito');}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.cantidad,0),subtotal=cart.reduce((sum,item)=>sum+item.precioOriginal*item.cantidad,0),descuento=cart.reduce((sum,item)=>sum+(item.precioOriginal-item.precio)*item.cantidad,0),productosTotal=subtotal-descuento,costoEnvio=selectedDelivery==='DOMICILIO'?(productosTotal>200?0:25):0,total=productosTotal+costoEnvio;document.querySelectorAll('#cartCount').forEach(el=>el.textContent=count);document.querySelectorAll('[data-cart-label]').forEach(el=>el.textContent=money(total));document.querySelectorAll('#cartButton').forEach(button=>button.setAttribute('aria-label',count?`Abrir carrito: ${count} productos, total ${money(total)}`:'Abrir carrito'));document.querySelector('#cartSubtotal').textContent=money(total);const discountEl=document.querySelector('#cartDiscount'),shippingEl=document.querySelector('#cartShipping');if(discountEl)discountEl.textContent=`-${money(descuento)}`;if(shippingEl)shippingEl.textContent=selectedDelivery?(costoEnvio?'Q25.00':'Gratis'):'—';document.querySelector('#cartItems').innerHTML=cart.length?cart.map(item=>{const id=escapeHtml(String(item.producto_id)),name=escapeHtml(String(item.nombre||'Producto')),image=escapeHtml(safeImageUrl(item.image)),quantity=Math.max(1,Math.min(99,Math.floor(Number(item.cantidad)||1)));return `<div class="cart-line"><img src="${image}" alt="${name}"><div><span>${name}</span><strong>${money(item.precio)}${item.precioOferta?` <small class="old-price">${money(item.precioOriginal)}</small>`:''}</strong><div class="quantity-control"><button data-quantity="-1" data-product="${id}">−</button><b>${quantity}</b><button data-quantity="1" data-product="${id}">+</button></div></div><button class="remove" data-remove="${id}" aria-label="Eliminar ${name}">×</button></div>`}).join(''):'<p class="empty-cart">Aún no agregaste productos.</p>';document.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{cart=cart.filter(item=>item.producto_id!==button.dataset.remove);guardarCarrito();renderCart()}));document.querySelectorAll('[data-quantity]').forEach(button=>button.addEventListener('click',()=>{const item=cart.find(entry=>entry.producto_id===button.dataset.product);if(!item)return;item.cantidad=Math.max(1,Math.min(99,item.cantidad+Number(button.dataset.quantity)));guardarCarrito();renderCart()}));}
function toggleCart(open){document.querySelector('#cartDrawer').classList.toggle('open',open);document.querySelector('#overlay').classList.toggle('open',open);document.querySelector('#cartDrawer').setAttribute('aria-hidden',!open)}
function showToast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
const mapProviders={google:{embed:'https://www.google.com/maps?q=JCX5%2B6HW%20San%20Mart%C3%ADn%20Librer%C3%ADa%20y%20Papeler%C3%ADa%2C%20Cdad.%20de%20Guatemala&output=embed',link:'https://www.google.com/maps/search/?api=1&query=JCX5%2B6HW%20San%20Mart%C3%ADn%20Librer%C3%ADa%20y%20Papeler%C3%ADa%2C%20Cdad.%20de%20Guatemala',label:'Abrir ubicación en Google Maps →'},waze:{embed:'https://embed.waze.com/iframe?zoom=16&lat=14.648101&lon=-90.591137&ct=livemap',link:'https://waze.com/ul?ll=14.648101%2C-90.591137&navigate=yes',label:'Abrir ubicación en Waze →'}};
document.querySelectorAll('[data-map-provider]').forEach(button=>button.addEventListener('click',()=>{const provider=mapProviders[button.dataset.mapProvider],map=document.querySelector('#storeMap'),link=document.querySelector('#mapOpenLink'),wazeLaunch=document.querySelector('#wazeMapLaunch');if(!provider||!map||!link)return;map.src=provider.embed;link.href=provider.link;link.textContent=provider.label;if(wazeLaunch)wazeLaunch.hidden=button.dataset.mapProvider!=='waze';document.querySelectorAll('[data-map-provider]').forEach(item=>item.classList.toggle('active',item===button));}));
renderFilters();renderProducts();
setupDraggableCarousels();
loadEditorialPromosFromSupabase();subscribeToEditorialPromoChanges();
Promise.all([loadCategoriesFromSupabase(),loadBrandsFromSupabase()]).then(async()=>{await loadProductsFromSupabase();renderCatalogDiscovery();});subscribeToCategoryChanges();subscribeToBrandChanges();subscribeToProductChanges();
loadBannersFromSupabase();subscribeToBannerChanges();loadHomeAnnouncements();subscribeToHomeAnnouncementChanges();
if(hasCatalogPage){document.querySelector('#smartFilters').addEventListener('change',event=>{const input=event.target;if(input.matches('[data-smart-sort]')){filterState.sort=input.value;refreshCatalog();return;}if(input.matches('[data-smart-filter]')){const key=input.dataset.smartFilter,value=input.value;if(key==='categoryId'){filterState.categoryId=value;filterState.subcategories.clear();activeCategory=categoryName(value);}else input.checked?filterState[key].add(value):filterState[key].delete(value);refreshCatalog();return;}if(input.matches('[data-price-bound]')){const value=input.value===''?null:Math.max(0,Number(input.value));filterState[input.dataset.priceBound==='min'?'minPrice':'maxPrice']=Number.isFinite(value)?value:null;if(filterState.minPrice!==null&&filterState.maxPrice!==null&&filterState.minPrice>filterState.maxPrice)filterState.maxPrice=filterState.minPrice;refreshCatalog();}});document.querySelector('#activeFilterChips').addEventListener('click',event=>{const button=event.target.closest('[data-remove-filter]');if(!button)return;const key=button.dataset.removeFilter;if(key==='categoryId'){filterState.categoryId=null;filterState.subcategories.clear();activeCategory='Todos';}else if(key==='price'){filterState.minPrice=null;filterState.maxPrice=null;}else filterState[key].delete(button.dataset.value);refreshCatalog();});document.querySelector('#resetFilters').addEventListener('click',()=>{filterState.sort='';filterState.categoryId=null;filterState.subcategories.clear();filterState.brands.clear();filterState.colors.clear();filterState.pieces.clear();filterState.minPrice=null;filterState.maxPrice=null;activeCategory='Todos';activeBrandSlug='';query='';document.querySelector('#searchInput').value='';refreshCatalog();});}
function toggleFilterSheet(open){if(!hasCatalogPage)return;document.body.classList.toggle('filters-open',open);document.querySelector('#catalogFilters').setAttribute('aria-hidden',String(!open));}
if(hasCatalogPage){document.querySelector('#openFilters').addEventListener('click',()=>toggleFilterSheet(true));document.querySelector('#closeFilters').addEventListener('click',()=>toggleFilterSheet(false));document.querySelector('#filterSheetOverlay').addEventListener('click',()=>toggleFilterSheet(false));document.querySelector('#mobileSort').addEventListener('change',event=>{filterState.sort=event.target.value;refreshCatalog();});}
if(hasCatalogPage){document.querySelectorAll('.catalog-pagination').forEach(nav=>nav.addEventListener('click',event=>{const button=event.target.closest('[data-page]');if(!button||button.disabled)return;currentPage=Number(button.dataset.page);renderProducts();document.querySelector('#productGrid').scrollIntoView({behavior:'smooth',block:'start'});}));}
document.querySelector('#searchButton').addEventListener('click',()=>{query=document.querySelector('#searchInput').value;if(!hasCatalogPage){window.location.href=`catalogo.html?buscar=${encodeURIComponent(query)}`;return;}activeCategory='Todos';currentPage=1;renderFilters();renderProducts();document.querySelector('#catalogo').scrollIntoView()});
document.querySelector('#searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')document.querySelector('#searchButton').click()});
document.querySelector('#cartButton').addEventListener('click',()=>toggleCart(true));document.querySelector('#closeCart').addEventListener('click',()=>toggleCart(false));document.querySelector('#overlay').addEventListener('click',()=>toggleCart(false));
renderCart();
const deliveryCostLabel=document.querySelector('input[name="deliveryMethod"][value="DOMICILIO"]')?.closest('label')?.querySelector('b');if(deliveryCostLabel)deliveryCostLabel.textContent='Q25 · gratis si supera Q200';
document.querySelectorAll('input[name="deliveryMethod"]').forEach(input=>input.addEventListener('change',event=>{selectedDelivery=event.target.value;renderCart()}));
document.querySelectorAll('input[name="paymentMethod"]').forEach(input=>input.addEventListener('change',event=>{selectedPayment=event.target.value;renderCart()}));
document.querySelector('#checkoutButton').addEventListener('click',async()=>{if(!cart.length)return showToast('Tu carrito está vacío.');const totalCarrito=cart.reduce((sum,item)=>sum+Number(item.precio)*item.cantidad,0);if(!selectedDelivery)return showToast('Selecciona si deseas recoger en tienda o envío a domicilio.');const pedidoMinimo=selectedDelivery==='RETIRO_TIENDA'?1:100;if(totalCarrito<pedidoMinimo)return showToast(`El pedido mínimo para ${selectedDelivery==='RETIRO_TIENDA'?'recoger en tienda':'envío a domicilio'} es de ${money(pedidoMinimo)}. Te faltan ${money(pedidoMinimo-totalCarrito)}.`);if(!selectedPayment)return showToast('Selecciona el método de pago.');const {data:{user}}=await supabaseClient.auth.getUser();if(!user){window.location.href=`login.html?returnTo=${encodeURIComponent(window.location.pathname.split('/').pop()||'index.html')}`;return}const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;if(cart.some(item=>!uuid.test(item.producto_id)))return showToast('El checkout estará disponible al conectar el catálogo real de Supabase.');const button=document.querySelector('#checkoutButton');button.disabled=true;button.textContent='Verificando inventario…';const {data,error}=await supabaseClient.rpc('crear_pedido_ecommerce',{p_items:cart.map(item=>({producto_id:item.producto_id,cantidad:item.cantidad})),p_metodo_entrega:selectedDelivery,p_metodo_pago:selectedPayment});button.disabled=false;button.textContent='Confirmar pedido';if(error)return showToast(error.message);cart=[];guardarCarrito();renderCart();toggleCart(false);showToast(`Pedido ${data.numero} creado correctamente.`)});
const newsletterForm=document.querySelector('#newsletter');if(newsletterForm)newsletterForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,email=form.querySelector('input[type="email"]')?.value.trim(),button=form.querySelector('button');if(!supabaseClient)return showToast('No pudimos conectar el newsletter. Inténtalo nuevamente.');button.disabled=true;const {error}=await supabaseClient.rpc('suscribir_newsletter',{p_correo:email});button.disabled=false;if(error)return showToast(error.message||'No pudimos registrar tu correo. Inténtalo nuevamente.');form.reset();showToast('¡Listo! Te suscribiste a nuestras novedades.')});
document.querySelector('#menuButton').addEventListener('click',()=>{
  const header=document.querySelector('.site-header');
  const isOpen=header.classList.toggle('menu-open');
  document.querySelector('#menuButton').setAttribute('aria-label',isOpen?'Cerrar menú':'Abrir menú');
});
document.querySelector('#favoritesButton')?.addEventListener('click',()=>{window.location.href='mi-cuenta.html?tab=favoritos'});
function applyCategoryFromUrl(attempt=0){if(!hasCatalogPage)return;const slug=pageParams.get('categoria');if(!slug)return;if(!remoteCategories.length){if(attempt<20)setTimeout(()=>applyCategoryFromUrl(attempt+1),250);return;}const category=remoteCategories.find(item=>item.slug===slug);if(category)selectCategoryFromHeader(category.nombre);}
function applyBrandFromUrl(attempt=0){if(!hasCatalogPage||!activeBrandSlug)return;if(!remoteBrands.length){if(attempt<20)setTimeout(()=>applyBrandFromUrl(attempt+1),250);return;}const brand=remoteBrands.find(item=>item.slug===activeBrandSlug);if(!brand)return;filterState.brands.clear();filterState.brands.add(brand.id);refreshCatalog();}
setTimeout(()=>applyCategoryFromUrl(),300);
setTimeout(()=>applyBrandFromUrl(),350);
document.querySelector('#categoryNav').addEventListener('click',event=>{
  const link=event.target.closest('a');
  if(!link)return;
  event.preventDefault();
  if(link.classList.contains('sale-link')){
    if(!hasCatalogPage){window.location.href='catalogo.html?destacados=1';return;}
    filterState.featured=true;refreshCatalog();return;
  }
  const name=link.dataset.category||'';
  if(!hasCatalogPage){
    const category=remoteCategories.find(item=>item.nombre===name);
    window.location.href=category?.slug?`catalogo.html?categoria=${encodeURIComponent(category.slug)}`:'catalogo.html';
    return;
  }
  selectCategoryFromHeader(name);
  document.querySelector('.site-header').classList.remove('menu-open');
});

function configureFeaturedNavigation(){const link=document.querySelector('#categoryNav .sale-link');if(!link)return;link.href='catalogo.html?destacados=1';link.dataset.featuredNav='true';}
const categoryNav=document.querySelector('#categoryNav');new MutationObserver(configureFeaturedNavigation).observe(categoryNav,{childList:true,subtree:true});configureFeaturedNavigation();

function ensureFeaturedCatalogFilter(){
  if(!hasCatalogPage)return;
  const host=document.querySelector('#smartFilters');
  if(!host||host.querySelector('[data-featured-filter]'))return;
  host.insertAdjacentHTML('beforeend',accordion('Destacados',`<div class="filter-options"><label class="filter-option ${filterState.featured?'is-selected':''}"><input type="checkbox" data-featured-filter ${filterState.featured?'checked':''}><span>Solo productos destacados</span></label></div>`));
}
if(hasCatalogPage){
  const featuredFilterHost=document.querySelector('#smartFilters');
  new MutationObserver(ensureFeaturedCatalogFilter).observe(featuredFilterHost,{childList:true});
  featuredFilterHost.addEventListener('change',event=>{if(!event.target.matches('[data-featured-filter]'))return;filterState.featured=event.target.checked;refreshCatalog();});
  document.querySelector('#resetFilters').addEventListener('click',()=>{if(filterState.featured){filterState.featured=false;refreshCatalog();}});
  ensureFeaturedCatalogFilter();
}

// Enlaces institucionales compartidos por todos los pies de página del e-commerce.
const footerGrid=document.querySelector('footer .footer-grid');
if(footerGrid&&!footerGrid.querySelector('[data-footer-nosotros]')){
  const aboutLinks=document.createElement('div');
  aboutLinks.dataset.footerNosotros='true';
  aboutLinks.innerHTML='<strong>Nosotros</strong><a href="nosotros-historia.html">Historia</a><a href="nosotros-perfil.html">Perfil de la empresa</a><a href="nosotros-gobierno-etica.html">Gobierno y ética</a><a href="nosotros-clientes-operacion.html">Clientes y operación</a><a href="nosotros-cadena-suministro.html">Cadena de suministro</a><a href="nosotros-personas.html">Personas</a>';
  const help=Array.from(footerGrid.children).find(section=>section.querySelector(':scope > strong')?.textContent==='Ayuda');
  if(help&&!help.querySelector('a[href="terminos-condiciones.html"]'))help.insertAdjacentHTML('beforeend','<a href="terminos-condiciones.html">Términos y condiciones</a>');
  footerGrid.insertBefore(aboutLinks,help||null);
}
const footerHelp=document.querySelector('footer .footer-grid > div:nth-last-child(2)');
if(footerHelp&&footerHelp.querySelector(':scope > strong')?.textContent==='Ayuda'&&!footerHelp.querySelector('a[href="aviso-privacidad.html"]')){
  const termsLink=footerHelp.querySelector('a[href="terminos-condiciones.html"]');
  if(termsLink)termsLink.insertAdjacentHTML('afterend','<a href="aviso-privacidad.html">Aviso de privacidad</a>');
}
const footerHelpRoutes={'Envíos y entregas':'envios-entregas.html','Cambios y devoluciones':'cambios-devoluciones.html','Contáctanos':'contacto.html'};
document.querySelectorAll('footer a').forEach(link=>{const route=footerHelpRoutes[link.textContent.trim()];if(route)link.href=route;});
document.querySelectorAll('footer a').forEach(link=>{if(link.textContent.trim()==='Inspiración')link.remove();});
const storeHours=Array.from(document.querySelectorAll('.visit-us-detail')).find(detail=>detail.textContent.includes('Horario'))?.querySelector('span:nth-child(2)');
if(storeHours)storeHours.innerHTML='<strong>Horario</strong>Lunes a Domingo: 6:00 AM - 8:00 PM';
